services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-qa-app
    ports:
      - "8501:8501"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://host.docker.internal:11434
      - DATA_DIR=/app/data
    volumes:
      # Mount data directory (contains pdf_pages for vision branch)
      - ./data:/app/data:ro
      # Optional: Mount app code for development (comment out for production)
      # - ./app:/app/app:ro
    depends_on:
      - qdrant
    networks:
      - rag-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qa-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      # Persist Qdrant data (collections, vectors, indices)
      - qdrant_data:/qdrant/storage
    networks:
      - rag-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  rag-network:
    driver: bridge
    name: rag-network

volumes:
  qdrant_data:
    name: rag-qdrant-data
